apiVersion: v1
kind: Service
metadata:
    name: productsservice
    labels:
        app: productsservice
spec:
    type: NodePort
    ports:
        - port: 8071
          targetPort: 8071
          nodePort: 30290
    selector:
        app: productsservice